### ISSUE TITLE
Warning about trivially true equals predicates

### ISSUE THREAD

**Issue by kaelte** [zzeekk/spark-temporalquery#13]
When running the test cases quite a few warnings like this are uttered:
```
[ScalaTest-main-running-TemporalQueryUtilTest] WARN  org.apache.spark.sql.Column - Constructing trivially true equals predicate, 'id#26 = id#26'. Perhaps you need to use aliases.
```
It would be nice to avoid these warnings.

**Comment by zzeekk** [comment]
Seems to be an old issue with Spark and self joins: 
https://issues.apache.org/jira/browse/SPARK-6459
