### ISSUE TITLE
temporalCleanupExtend: not(fillGapsWithNull) ⟶ not(extend)

### ISSUE THREAD

**Issue by kaelte** [zzeekk/spark-temporalquery#15]
If `fillGapsWithNull = false` then `extend = true` has not effect. This is due to

https://github.com/zzeekk/spark-temporalquery/blob/1598eb8a891ae624f3a3bcb50e77fd1645bae1f9/src/main/scala/ch/zzeekk/spark/temporalquery/TemporalQueryUtil.scala#L317

Is this the expected behaviour of `temporalCleanupExtend`?

**Comment by zzeekk** [comment]
You're right, the sematic is probably not very clear, but yes it's actually expected: Extend is on top of fillGapsWithNull, it actually adds "gaps" at begin and end of the timeline, if they are not "filled with null" afterwards, they are lost again.
Do you have a suggestion for a better interface?

**Comment by kaelte** [comment]
Not really. If the case of `not(fillGapsWithNull) && extend` is not needed I think we should leave it as it is because to cover it a more complicated implementation will be neede.
But we must document it in `README.md`. There the 2 parameters in question are not even mentioned!

**Comment by zzeekk** [comment]
We could log a warning in this case, see PR #18
