### ISSUE TITLE
temporalCleanupExtend: rnkExpressions ignores column fromColName

### ISSUE THREAD

**Issue by kaelte** [zzeekk/spark-temporalquery#22]
```
df: struct<id:int,val:string,gueltig_ab:timestamp,gueltig_bis:timestamp>
+---+---+-------------------+-------------------+
|id |val|gueltig_ab         |gueltig_bis        |
+---+---+-------------------+-------------------+
|1  |S  |0001-01-01 00:00:00|9999-12-31 00:00:00|
|1  |X  |2020-07-01 00:00:00|9999-12-31 00:00:00|
+---+---+-------------------+-------------------+
```

`df.temporalCleanupExtend(Seq("id"),Seq(col(defaultConfig.fromColName)))` results wrongly to
```
+---+---+-------------------+-----------------------+--------+
|id |val|gueltig_ab         |gueltig_bis            |_defined|
+---+---+-------------------+-----------------------+--------+
|1  |S  |0001-01-01 00:00:00|2020-06-30 23:59:59.999|true    |
|1  |X  |2020-07-01 00:00:00|9999-12-31 00:00:00    |true    |
+---+---+-------------------+-----------------------+--------+
```

Actually the result is not deterministic!

Because the usage of `temporalUnifyRangesImpl` to build `df_join` and thus `df_agg` cuts the time interval with `val = S` into 2 pieces so that X and S start at the same time, i.e. `2020-07-01`:
```
df_agg:
+---+---+-------------------+-----------------------+--------+
|id |val|gueltig_ab         |gueltig_bis            |_defined|
+---+---+-------------------+-----------------------+--------+
|1  |S  |0001-01-01 00:00:00|2020-06-30 23:59:59.999|true    |
|1  |X  |2020-07-01 00:00:00|9999-12-31 00:00:00    |true    |
|1  |S  |2020-07-01 00:00:00|9999-12-31 00:00:00    |true    |
+---+---+-------------------+-----------------------+--------+
```

Hence the subsequent analytical function `row_number.over(fenestra.orderBy(rnkExpressions: _*))` is not deterministic because `gueltig_ab`is the only expression.

## Possible Solution:
Remove the call to temporalUnifyRangesImpl.
But that implies the removal off aggregation.

**Comment by kaelte** [comment]
3 failing test cases add to branch `bug/issue_22`

https://github.com/zzeekk/spark-temporalquery/blob/5f1e5900f80a522902771b831231df39abdd7aa0/src/test/scala/ch.zzeekk.spark.temporalquery/TemporalQueryUtilTest.scala#L195

https://github.com/zzeekk/spark-temporalquery/blob/5f1e5900f80a522902771b831231df39abdd7aa0/src/test/scala/ch.zzeekk.spark.temporalquery/TemporalQueryUtilTest.scala#L261

https://github.com/zzeekk/spark-temporalquery/blob/5f1e5900f80a522902771b831231df39abdd7aa0/src/test/scala/ch.zzeekk.spark.temporalquery/TemporalQueryUtilTest.scala#L278

**Comment by zzeekk** [comment]
Another solution would be to keep the original from/toCol for ranking... and switch to the unified from/toCol in the end. So we could use original from/toCol for ranking.

**Comment by kaelte** [comment]
> Another solution would be to keep the original from/toCol for ranking... and switch to the unified from/toCol in the end. So we could use original from/toCol for ranking.

But would you not need to distinct cases: whether from/toCol appears in rank expression or not?

**Comment by kaelte** [comment]
Possible solution found, but I would like to see some more test cases.

Rank original data frame df
https://github.com/zzeekk/spark-temporalquery/blob/938fb320a280cef4341728acaf07b7157d57cb65/src/main/scala/ch/zzeekk/spark/temporalquery/TemporalQueryUtil.scala#L240-L246

and then select for each time interval the record with minimal rank `_rnk` from the unified `df_agg`
https://github.com/zzeekk/spark-temporalquery/blob/938fb320a280cef4341728acaf07b7157d57cb65/src/main/scala/ch/zzeekk/spark/temporalquery/TemporalQueryUtil.scala#L257-L262

We need to call `temporalUnifyRangesImpl` in any case, even when `aggExpressions = Seq().

Why does spark not know the Window function [first_value](https://www.postgresql.org/docs/12/functions-window.html) ?

**Comment by kaelte** [comment]
Complex test case added: https://github.com/zzeekk/spark-temporalquery/commit/4350e972eb81ca86dcc4df4fd0a0f60821b8f6ff

**Comment by kaelte** [comment]
Eine bessere Lösung, die nur einmal das Ranking durchführt:
https://github.com/zzeekk/spark-temporalquery/blob/b688bde2e9f9dc1f5a82c46f93643fe0a145bd0e/src/main/scala/ch/zzeekk/spark/temporalquery/TemporalQueryUtil.scala#L246-L257

**Comment by zzeekk** [comment]
> Why does spark not know the Window function [first_value](https://www.postgresql.org/docs/12/functions-window.html) ?

Spark has functions first/last, that should be the same, isn't it?

**Comment by kaelte** [comment]
> > Why does spark not know the Window function [first_value](https://www.postgresql.org/docs/12/functions-window.html) ?
> 
> Spark has functions first/last, that should be the same, isn't it?

According to [Spark ScalaDoc](https://spark.apache.org/docs/2.3.1/api/scala/index.html#org.apache.spark.sql.functions$) they are aggregations, not analytical/window functions:

> def first(e: Column): Column
>
> Aggregate function: returns the first value in a group.
>
> The function by default returns the first values it sees. It will return the first non-null value it sees when ignoreNulls is set to true. If all values are null, then null is returned.

**Comment by kaelte** [comment]
Fix merged to master
