### ISSUE TITLE
Do not use year 0

### ISSUE THREAD

**Issue by kaelte** [zzeekk/spark-temporalquery#23]
https://github.com/zzeekk/spark-temporalquery/blob/e5d91578b93f0f281e4957a14d108b317d1c0e12/src/main/scala/ch/zzeekk/spark/temporalquery/TemporalQueryUtil.scala#L26

Java/Scala and Hive do not treat year 0 properly but do not throw an exception either:

## Scala
```
val firstDayString = "0000-01-01 00:00:00"
val firstDay = Timestamp.valueOf(firstDayString)
val firstDay_2 = Timestamp.valueOf(firstDay.toString)
val areEqual = firstDay == firstDay_2
```

### Ausgabe
```
firstDayString: String = 0000-01-01 00:00:00
firstDay: java.sql.Timestamp = 0001-01-01 00:00:00.0
firstDay_2: java.sql.Timestamp = 0001-01-01 00:00:00.0
areEqual: Boolean = false
```

## Hive
We have a table T in which we have records in year 0 but which are displayed as year 1:

```
select * from T where validFrom = timestamp '0000-01-01 00:00:00' ;

--> shows record with validFrom = '0001-01-01 00:00:00'
```

but you cannot find records in year 1:

```
select * from T where validFrom = timestamp '0001-01-01 00:00:00' ;

--> empty result
```

We need to set minDate yo year 1!

**Comment by zzeekk** [comment]
Interesting. According to Hive documentation thei support as well year 0000 for Dates, see https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Types, but i'm not sure for Timestamp. Using 0001 is ok for me.
