### ISSUE TITLE
temporalInnerJoin does not propagate alias on join column anymore

### ISSUE THREAD

**Issue by kaelte** [zzeekk/spark-temporalquery#30]
The following lines of code used to work in release 0.9.5.2 but does not work anymore, since commit 66dcef0. That is why an application of a user does not work anymore!

```
val actual = dfLeft.as("dfL").temporalInnerJoin(dfRight.as("dfR"),Seq("id"))
actual.printSchema()
actual.select($"id",$"dfL.wert_l",$"dfR.wert_r").show(false)
actual.select($"dfL.id",$"dfL.wert_l",$"dfR.wert_r").show(false)
```

Until and including commit de756a9
```
root
 |-- id: integer (nullable = false)
 |-- wert_l: double (nullable = false)
 |-- wert_r: double (nullable = true)
 |-- gueltig_ab: timestamp (nullable = true)
 |-- gueltig_bis: timestamp (nullable = true)

+---+------+------+
|id |wert_l|wert_r|
+---+------+------+
|0  |4.2   |97.15 |
|0  |4.2   |97.15 |
|0  |4.2   |97.15 |
+---+------+------+

+---+------+------+
|id |wert_l|wert_r|
+---+------+------+
|0  |4.2   |97.15 |
|0  |4.2   |97.15 |
|0  |4.2   |97.15 |
+---+------+------+
```

From commit 66dcef0 onwards
```
root
 |-- id: integer (nullable = false)
 |-- wert_l: double (nullable = false)
 |-- wert_r: double (nullable = true)
 |-- gueltig_ab: timestamp (nullable = true)
 |-- gueltig_bis: timestamp (nullable = true)

+---+------+------+
|id |wert_l|wert_r|
+---+------+------+
|0  |4.2   |97.15 |
|0  |4.2   |97.15 |
|0  |4.2   |97.15 |
+---+------+------+

cannot resolve '`dfL.id`' given input columns: [dfR.wert_r, gueltig_bis, dfL.wert_l, id, gueltig_ab];;
'Project ['dfL.id, wert_l#12, wert_r#29]
...
```

But commit 66dcef0 removes only some dataFrame.show() commands which I used during development ! 

Why does the behaviour of `temporalInnerJoin` change?

**Comment by kaelte** [comment]
Side remark: We do not have any test case for `temporalInnerJoin`!
I have added one including the alias propagation in the new branch [question/issue_30 ](https://github.com/zzeekk/spark-temporalquery/tree/question/issue_30).

**Comment by zzeekk** [comment]
The error message show that id, gueltig_ab/bis have no table alias after the join:
`cannot resolve 'dfL.id' given input columns: [dfR.wert_r, gueltig_bis, dfL.wert_l, id, gueltig_ab]`
Column id has no table alias because of 
`val commonCols: Array[Column] = dfCommonColNames.map(colName => coalesce(df1(colName),df2(colName)).as(colName))`
It was introduced with commit 57f6f3eb15696cf9b6681d7d918d067d25cec69a "temporalFullJoin and temporalRightJoin implemented".
Probably it's not a good idea to consolidate common columns. We must keep both columns with alias. That would also be normal join behaviour. 
@kaelte: what's your opinion on this?

**Comment by kaelte** [comment]
> Probably it's not a good idea to consolidate common columns. We must keep both columns with alias. That would also be normal join behaviour.

The normal join behaviour is to consolidate join columns:

```
 dfLeft.join(right=dfRight, usingColumns=Seq("id"), joinType="inner").show(false)

+---+-------------------+-----------------------+------+-------------------+-----------------------+------+
|id |gueltig_ab         |gueltig_bis            |wert_l|gueltig_ab         |gueltig_bis            |wert_r|
+---+-------------------+-----------------------+------+-------------------+-----------------------+------+
|0  |2017-12-10 00:00:00|2018-12-08 23:59:59.999|4.2   |2018-01-01 00:00:00|2018-01-31 23:59:59.999|97.15 |
|0  |2017-12-10 00:00:00|2018-12-08 23:59:59.999|4.2   |2018-06-01 05:24:11|2018-10-23 03:50:09.999|97.15 |
|0  |2017-12-10 00:00:00|2018-12-08 23:59:59.999|4.2   |2018-10-23 03:50:10|2019-12-31 23:59:59.999|97.15 |
|0  |2017-12-10 00:00:00|2018-12-08 23:59:59.999|4.2   |2020-01-01 00:00:00|9999-12-31 00:00:00    |97.15 |
+---+-------------------+-----------------------+------+-------------------+-----------------------+------+
```
Note that gueltig_ab and gueltig_bis are just ordinary columns for `.join`.

**Comment by kaelte** [comment]
As a special feature the result could contain 3 versions of the join columns: dfLeft, dfRight and dfConsolidated.

On the other hand, why would you give a data frame an alias, e.g. to dfLeft, before using temporalJoin when you use the alias only later. Note that in this join the alias is not used.

> We must keep both columns with alias.

Only the left alias propagated in previous versions to the result.

**Comment by zzeekk** [comment]
@kaelte: No, consolidation is only done with "using" syntax, but normal join is givin a join condition with "on". 
For temporalquery we just have to decide in which mode we want to operate... or maybe have a parameter for join?

**Comment by kaelte** [comment]
For outer join the result need to have consolidated columns, i.e. without any NULL values.

Additionally the result may contain 2 further columns for each join column, e.g. id, dfLeft.id, dfRight.id

Then we would not need a parameter but the user can select the desired columns.
